version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: joke
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jokedb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/jokedb

volumes:
  db_data:
